DROP TABLE IF EXISTS "HERRAMIENTAS";
CREATE TABLE "HERRAMIENTAS"(
ID_HER INTEGER NOT NULL,
MARCA TEXT NOT NULL,
MODELO TEXT NOT NULL,
PRECIO INTEGER NOT NULL,
PRIMARY KEY ("ID_HER")
);
INSERT INTO "HERRAMIENTAS" VALUES(100,"ROSAS","HD-572",15500);
SELECT *FROM "HERRAMIENTAS";
INSERT INTO "HERRAMIENTAS" (MARCA,MODELO,PRECIO) VALUES ("CORREA","MAN-777",15000);
SELECT *FROM "HERRAMIENTAS";
INSERT INTO "HERRAMIENTAS" (MARCA,MODELO,PRECIO) VALUES ("CAT","BT-678",30000);
SELECT *FROM "HERRAMIENTAS";
INSERT INTO "HERRAMIENTAS" (MARCA,MODELO,PRECIO) VALUES ("TVZ","HG-99",25000);
SELECT *FROM "HERRAMIENTAS";
INSERT INTO "HERRAMIENTAS" (MARCA,MODELO,PRECIO) VALUES ("HDD","TZ-1040",28000);
SELECT *FROM "HERRAMIENTAS";
ALTER TABLE "HERRAMIENTAS" ADD COLUMN STOCK INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "HERRAMIENTAS" ADD COLUMN PRUEBA INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "HERRAMIENTAS" DROP COLUMN PRUEBA;
DELETE FROM "HERRAMIENTAS" WHERE ID_HER = 101;
